# Generated by Django 3.1.6 on 2021-02-07 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, size=None)),
                ('iswc', models.CharField(blank=True, default='', max_length=11)),
            ],
        ),
    ]
